In [7]:
%pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: randomuser
  Building wheel for randomuser (pyproject.toml): started
  Building wheel for randomuser (pyproject.toml): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5128 sha256=5f118aadddca7b9d0f0a7d0ce53b4a560c09b5739c5c56aeba46aee5e71d8475
  Stored in directory: c:\users\jdarl\appdata\local\pip\cache\wheels\be\62\c8\71e1b48f4758ea5b78af7595d87178f628cde315a3326610ee
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from randomuser import RandomUser

In [10]:
r = RandomUser()
r

In [23]:
users = r.generate_users(1000)

In [24]:
users

[<randomuser.RandomUser at 0x1a81253a1e0>,
 <randomuser.RandomUser at 0x1a812538650>,
 <randomuser.RandomUser at 0x1a81253a2a0>,
 <randomuser.RandomUser at 0x1a812538ce0>,
 <randomuser.RandomUser at 0x1a812538980>,
 <randomuser.RandomUser at 0x1a8125380e0>,
 <randomuser.RandomUser at 0x1a812539df0>,
 <randomuser.RandomUser at 0x1a8143ff140>,
 <randomuser.RandomUser at 0x1a8143ff1a0>,
 <randomuser.RandomUser at 0x1a8143ff170>,
 <randomuser.RandomUser at 0x1a8143ff1d0>,
 <randomuser.RandomUser at 0x1a8143ff200>,
 <randomuser.RandomUser at 0x1a8143ff230>,
 <randomuser.RandomUser at 0x1a8143ff260>,
 <randomuser.RandomUser at 0x1a8143ff290>,
 <randomuser.RandomUser at 0x1a8143ff2c0>,
 <randomuser.RandomUser at 0x1a8143ff2f0>,
 <randomuser.RandomUser at 0x1a8143ff320>,
 <randomuser.RandomUser at 0x1a8143ff350>,
 <randomuser.RandomUser at 0x1a8143ff380>,
 <randomuser.RandomUser at 0x1a8143ff3b0>,
 <randomuser.RandomUser at 0x1a8143ff3e0>,
 <randomuser.RandomUser at 0x1a8143ff410>,
 <randomuser.RandomUser at 0x1a8143ff440>,
 <randomuser.RandomUser at 0x1a8143ff470>,
 <randomuser.RandomUser at 0x1a8143ff4a0>,
 <randomuser.RandomUser at 0x1a8143ff4d0>,
 <randomuser.RandomUser at 0x1a8143ff500>,
 <randomuser.RandomUser at 0x1a8143ff530>,
 <randomuser.RandomUser at 0x1a8143ff560>,
 <randomuser.RandomUser at 0x1a8143ff590>,
 <randomuser.RandomUser at 0x1a8143ff5c0>,
 <randomuser.RandomUser at 0x1a8143ff5f0>,
 <randomuser.RandomUser at 0x1a8143ff620>,
 <randomuser.RandomUser at 0x1a8143ff650>,
 <randomuser.RandomUser at 0x1a8143ff680>,
 <randomuser.RandomUser at 0x1a8143ff6b0>,
 <randomuser.RandomUser at 0x1a8143ff6e0>,
 <randomuser.RandomUser at 0x1a8143ff710>,
 <randomuser.RandomUser at 0x1a8143ff740>,
 <randomuser.RandomUser at 0x1a8143ff770>,
 <randomuser.RandomUser at 0x1a8143ff7a0>,
 <randomuser.RandomUser at 0x1a8143ff7d0>,
 <randomuser.RandomUser at 0x1a8143ff800>,
 <randomuser.RandomUser at 0x1a8143ff830>,
 <randomuser.RandomUser at 0x1a8143ff860>,
 <randomuser.RandomUser at 0x1a8143ff890>,
 <randomuser.RandomUser at 0x1a8143ff8c0>,
 <randomuser.RandomUser at 0x1a8143ff8f0>,
 <randomuser.RandomUser at 0x1a8143ff920>,
 <randomuser.RandomUser at 0x1a8143ff950>,
 <randomuser.RandomUser at 0x1a8143ff980>,
 <randomuser.RandomUser at 0x1a8143ff9b0>,
 <randomuser.RandomUser at 0x1a8143ff9e0>,
 <randomuser.RandomUser at 0x1a8143ffa10>,
 <randomuser.RandomUser at 0x1a8143ffa40>,
 <randomuser.RandomUser at 0x1a8143ffa70>,
 <randomuser.RandomUser at 0x1a8143ffaa0>,
 <randomuser.RandomUser at 0x1a8143ffad0>,
 <randomuser.RandomUser at 0x1a8143ffb00>,
 <randomuser.RandomUser at 0x1a8143ffb30>,
 <randomuser.RandomUser at 0x1a8143ffb60>,
 <randomuser.RandomUser at 0x1a8143ffb90>,
 <randomuser.RandomUser at 0x1a8143ffbc0>,
 <randomuser.RandomUser at 0x1a8143ffbf0>,
 <randomuser.RandomUser at 0x1a8143ffc20>,
 <randomuser.RandomUser at 0x1a8143ffc50>,
 <randomuser.RandomUser at 0x1a8143ffc80>,
 <randomuser.RandomUser at 0x1a8143ffcb0>,
 <randomuser.RandomUser at 0x1a8143ffce0>,
 <randomuser.RandomUser at 0x1a8143ffd10>,
 <randomuser.RandomUser at 0x1a8143ffd40>,
 <randomuser.RandomUser at 0x1a8143ffd70>,
 <randomuser.RandomUser at 0x1a8143ffda0>,
 <randomuser.RandomUser at 0x1a8143ffdd0>,
 <randomuser.RandomUser at 0x1a8143ffe00>,
 <randomuser.RandomUser at 0x1a8143ffe30>,
 <randomuser.RandomUser at 0x1a8143ffe60>,
 <randomuser.RandomUser at 0x1a8143ffe90>,
 <randomuser.RandomUser at 0x1a8143ffec0>,
 <randomuser.RandomUser at 0x1a8143ffef0>,
 <randomuser.RandomUser at 0x1a8143fff20>,
 <randomuser.RandomUser at 0x1a8143fff50>,
 <randomuser.RandomUser at 0x1a8143fff80>,
 <randomuser.RandomUser at 0x1a8143fffb0>,
 <randomuser.RandomUser at 0x1a8143fffe0>,
 <randomuser.RandomUser at 0x1a814418050>,
 <randomuser.RandomUser at 0x1a814418080>,
 <randomuser.RandomUser at 0x1a8144180b0>,
 <randomuser.RandomUser at 0x1a8144180e0>,
 <randomuser.RandomUser at 0x1a814418110>,
 <randomuser.RandomUser at 0x1a814418140>,
 <randomuser.RandomUser at 0x1a814418170>,
 <randomuser.RandomUser at 0x1a8144181a0>,
 <randomuser.RandomUser at 0x1a8144181d0>,
 <randomuser.RandomUser at 0x1a814418200>,
 <randomuser.RandomUser at 0x1a814418230>,
 <randomuser.RandomUser at 0x1a814418260>,
 <randomuser.RandomUser at 0x1a814418290>,
 <randomuser.RandomUser at 0x1a8144182c0>,
 <randomuser.RandomUser at 0x1a8144182f0>,
 <randomuser.RandomUser at 0x1a814418320>,
 <randomuser.RandomUser at 0x1a814418350>,
 <randomuser.RandomUser at 0x1a814418380>,
 <randomuser.RandomUser at 0x1a8144183b0>,
 <randomuser.RandomUser at 0x1a8144183e0>,
 <randomuser.RandomUser at 0x1a814418410>,
 <randomuser.RandomUser at 0x1a814418440>,
 <randomuser.RandomUser at 0x1a814418470>,
 <randomuser.RandomUser at 0x1a8144184a0>,
 <randomuser.RandomUser at 0x1a8144184d0>,
 <randomuser.RandomUser at 0x1a814418500>,
 <randomuser.RandomUser at 0x1a814418530>,
 <randomuser.RandomUser at 0x1a814418560>,
 <randomuser.RandomUser at 0x1a814418590>,
 <randomuser.RandomUser at 0x1a8144185c0>,
 <randomuser.RandomUser at 0x1a8144185f0>,
 <randomuser.RandomUser at 0x1a814418620>,
 <randomuser.RandomUser at 0x1a814418650>,
 <randomuser.RandomUser at 0x1a814418680>,
 <randomuser.RandomUser at 0x1a8144186b0>,
 <randomuser.RandomUser at 0x1a8144186e0>,
 <randomuser.RandomUser at 0x1a814418710>,
 <randomuser.RandomUser at 0x1a814418740>,
 <randomuser.RandomUser at 0x1a814418770>,
 <randomuser.RandomUser at 0x1a8144187a0>,
 <randomuser.RandomUser at 0x1a8144187d0>,
 <randomuser.RandomUser at 0x1a814418800>,
 <randomuser.RandomUser at 0x1a814418830>,
 <randomuser.RandomUser at 0x1a814418860>,
 <randomuser.RandomUser at 0x1a814418890>,
 <randomuser.RandomUser at 0x1a8144188c0>,
 <randomuser.RandomUser at 0x1a8144188f0>,
 <randomuser.RandomUser at 0x1a814418920>,
 <randomuser.RandomUser at 0x1a814418950>,
 <randomuser.RandomUser at 0x1a814418980>,
 <randomuser.RandomUser at 0x1a8144189b0>,
 <randomuser.RandomUser at 0x1a8144189e0>,
 <randomuser.RandomUser at 0x1a814418a10>,
 <randomuser.RandomUser at 0x1a814418a40>,
 <randomuser.RandomUser at 0x1a814418a70>,
 <randomuser.RandomUser at 0x1a814418aa0>,
 <randomuser.RandomUser at 0x1a814418ad0>,
 <randomuser.RandomUser at 0x1a814418b00>,
 <randomuser.RandomUser at 0x1a814418b30>,
 <randomuser.RandomUser at 0x1a814418b60>,
 <randomuser.RandomUser at 0x1a814418b90>,
 <randomuser.RandomUser at 0x1a814418bc0>,
 <randomuser.RandomUser at 0x1a814418bf0>,
 <randomuser.RandomUser at 0x1a814418c20>,
 <randomuser.RandomUser at 0x1a814418c50>,
 <randomuser.RandomUser at 0x1a814418c80>,
 <randomuser.RandomUser at 0x1a814418cb0>,
 <randomuser.RandomUser at 0x1a814418ce0>,
 <randomuser.RandomUser at 0x1a814418d10>,
 <randomuser.RandomUser at 0x1a814418d40>,
 <randomuser.RandomUser at 0x1a814418d70>,
 <randomuser.RandomUser at 0x1a814418da0>,
 <randomuser.RandomUser at 0x1a814418dd0>,
 <randomuser.RandomUser at 0x1a814418e00>,
 <randomuser.RandomUser at 0x1a814418e30>,
 <randomuser.RandomUser at 0x1a814418e60>,
 <randomuser.RandomUser at 0x1a814418e90>,
 <randomuser.RandomUser at 0x1a814418ec0>,
 <randomuser.RandomUser at 0x1a814418ef0>,
 <randomuser.RandomUser at 0x1a814418f20>,
 <randomuser.RandomUser at 0x1a814418f50>,
 <randomuser.RandomUser at 0x1a814418f80>,
 <randomuser.RandomUser at 0x1a814418fb0>,
 <randomuser.RandomUser at 0x1a814418fe0>,
 <randomuser.RandomUser at 0x1a814419010>,
 <randomuser.RandomUser at 0x1a814419040>,
 <randomuser.RandomUser at 0x1a814419070>,
 <randomuser.RandomUser at 0x1a8144190a0>,
 <randomuser.RandomUser at 0x1a8144190d0>,
 <randomuser.RandomUser at 0x1a814419100>,
 <randomuser.RandomUser at 0x1a814419130>,
 <randomuser.RandomUser at 0x1a814419160>,
 <randomuser.RandomUser at 0x1a814419190>,
 <randomuser.RandomUser at 0x1a8144191c0>,
 <randomuser.RandomUser at 0x1a8144191f0>,
 <randomuser.RandomUser at 0x1a814419220>,
 <randomuser.RandomUser at 0x1a814419250>,
 <randomuser.RandomUser at 0x1a814419280>,
 <randomuser.RandomUser at 0x1a8144192b0>,
 <randomuser.RandomUser at 0x1a8144192e0>,
 <randomuser.RandomUser at 0x1a814419310>,
 <randomuser.RandomUser at 0x1a814419340>,
 <randomuser.RandomUser at 0x1a814419370>,
 <randomuser.RandomUser at 0x1a8144193a0>,
 <randomuser.RandomUser at 0x1a8144193d0>,
 <randomuser.RandomUser at 0x1a814419400>,
 <randomuser.RandomUser at 0x1a814419430>,
 <randomuser.RandomUser at 0x1a814419460>,
 <randomuser.RandomUser at 0x1a814419490>,
 <randomuser.RandomUser at 0x1a8144194c0>,
 <randomuser.RandomUser at 0x1a8144194f0>,
 <randomuser.RandomUser at 0x1a814419520>,
 <randomuser.RandomUser at 0x1a814419550>,
 <randomuser.RandomUser at 0x1a814419580>,
 <randomuser.RandomUser at 0x1a8144195b0>,
 <randomuser.RandomUser at 0x1a8144195e0>,
 <randomuser.RandomUser at 0x1a814419610>,
 <randomuser.RandomUser at 0x1a814419640>,
 <randomuser.RandomUser at 0x1a814419670>,
 <randomuser.RandomUser at 0x1a8144196a0>,
 <randomuser.RandomUser at 0x1a8144196d0>,
 <randomuser.RandomUser at 0x1a814419700>,
 <randomuser.RandomUser at 0x1a814419730>,
 <randomuser.RandomUser at 0x1a814419760>,
 <randomuser.RandomUser at 0x1a814419790>,
 <randomuser.RandomUser at 0x1a8144197c0>,
 <randomuser.RandomUser at 0x1a8144197f0>,
 <randomuser.RandomUser at 0x1a814419820>,
 <randomuser.RandomUser at 0x1a814419850>,
 <randomuser.RandomUser at 0x1a814419880>,
 <randomuser.RandomUser at 0x1a8144198b0>,
 <randomuser.RandomUser at 0x1a8144198e0>,
 <randomuser.RandomUser at 0x1a814419910>,
 <randomuser.RandomUser at 0x1a814419940>,
 <randomuser.RandomUser at 0x1a814419970>,
 <randomuser.RandomUser at 0x1a8144199a0>,
 <randomuser.RandomUser at 0x1a8144199d0>,
 <randomuser.RandomUser at 0x1a814419a00>,
 <randomuser.RandomUser at 0x1a814419a30>,
 <randomuser.RandomUser at 0x1a814419a60>,
 <randomuser.RandomUser at 0x1a814419a90>,
 <randomuser.RandomUser at 0x1a814419ac0>,
 <randomuser.RandomUser at 0x1a814419af0>,
 <randomuser.RandomUser at 0x1a814419b20>,
 <randomuser.RandomUser at 0x1a814419b50>,
 <randomuser.RandomUser at 0x1a814419b80>,
 <randomuser.RandomUser at 0x1a814419bb0>,
 <randomuser.RandomUser at 0x1a814419be0>,
 <randomuser.RandomUser at 0x1a814419c10>,
 <randomuser.RandomUser at 0x1a814419c40>,
 <randomuser.RandomUser at 0x1a814419c70>,
 <randomuser.RandomUser at 0x1a814419ca0>,
 <randomuser.RandomUser at 0x1a814419cd0>,
 <randomuser.RandomUser at 0x1a814419d00>,
 <randomuser.RandomUser at 0x1a814419d30>,
 <randomuser.RandomUser at 0x1a814419d60>,
 <randomuser.RandomUser at 0x1a814419d90>,
 <randomuser.RandomUser at 0x1a814419dc0>,
 <randomuser.RandomUser at 0x1a814419df0>,
 <randomuser.RandomUser at 0x1a814419e20>,
 <randomuser.RandomUser at 0x1a814419e50>,
 <randomuser.RandomUser at 0x1a814419e80>,
 <randomuser.RandomUser at 0x1a814419eb0>,
 <randomuser.RandomUser at 0x1a814419ee0>,
 <randomuser.RandomUser at 0x1a814419f10>,
 <randomuser.RandomUser at 0x1a814419f40>,
 <randomuser.RandomUser at 0x1a814419f70>,
 <randomuser.RandomUser at 0x1a814419fa0>,
 <randomuser.RandomUser at 0x1a814419fd0>,
 <randomuser.RandomUser at 0x1a81441a000>,
 <randomuser.RandomUser at 0x1a81441a030>,
 <randomuser.RandomUser at 0x1a81441a060>,
 <randomuser.RandomUser at 0x1a81441a090>,
 <randomuser.RandomUser at 0x1a81441a0c0>,
 <randomuser.RandomUser at 0x1a81441a0f0>,
 <randomuser.RandomUser at 0x1a81441a120>,
 <randomuser.RandomUser at 0x1a81441a150>,
 <randomuser.RandomUser at 0x1a81441a180>,
 <randomuser.RandomUser at 0x1a81441a1b0>,
 <randomuser.RandomUser at 0x1a81441a1e0>,
 <randomuser.RandomUser at 0x1a81441a210>,
 <randomuser.RandomUser at 0x1a81441a240>,
 <randomuser.RandomUser at 0x1a81441a270>,
 <randomuser.RandomUser at 0x1a81441a2a0>,
 <randomuser.RandomUser at 0x1a81441a2d0>,
 <randomuser.RandomUser at 0x1a81441a300>,
 <randomuser.RandomUser at 0x1a81441a330>,
 <randomuser.RandomUser at 0x1a81441a360>,
 <randomuser.RandomUser at 0x1a81441a390>,
 <randomuser.RandomUser at 0x1a81441a3c0>,
 <randomuser.RandomUser at 0x1a81441a3f0>,
 <randomuser.RandomUser at 0x1a81441a420>,
 <randomuser.RandomUser at 0x1a81441a450>,
 <randomuser.RandomUser at 0x1a81441a480>,
 <randomuser.RandomUser at 0x1a81441a4b0>,
 <randomuser.RandomUser at 0x1a81441a4e0>,
 <randomuser.RandomUser at 0x1a81441a510>,
 <randomuser.RandomUser at 0x1a81441a540>,
 <randomuser.RandomUser at 0x1a81441a570>,
 <randomuser.RandomUser at 0x1a81441a5a0>,
 <randomuser.RandomUser at 0x1a81441a5d0>,
 <randomuser.RandomUser at 0x1a81441a600>,
 <randomuser.RandomUser at 0x1a81441a630>,
 <randomuser.RandomUser at 0x1a81441a660>,
 <randomuser.RandomUser at 0x1a81441a690>,
 <randomuser.RandomUser at 0x1a81441a6c0>,
 <randomuser.RandomUser at 0x1a81441a6f0>,
 <randomuser.RandomUser at 0x1a81441a720>,
 <randomuser.RandomUser at 0x1a81441a750>,
 <randomuser.RandomUser at 0x1a81441a780>,
 <randomuser.RandomUser at 0x1a81441a7b0>,
 <randomuser.RandomUser at 0x1a81441a7e0>,
 <randomuser.RandomUser at 0x1a81441a810>,
 <randomuser.RandomUser at 0x1a81441a840>,
 <randomuser.RandomUser at 0x1a81441a870>,
 <randomuser.RandomUser at 0x1a81441a8a0>,
 <randomuser.RandomUser at 0x1a81441a8d0>,
 <randomuser.RandomUser at 0x1a81441a900>,
 <randomuser.RandomUser at 0x1a81441a930>,
 <randomuser.RandomUser at 0x1a81441a960>,
 <randomuser.RandomUser at 0x1a81441a990>,
 <randomuser.RandomUser at 0x1a81441a9c0>,
 <randomuser.RandomUser at 0x1a81441a9f0>,
 <randomuser.RandomUser at 0x1a81441aa20>,
 <randomuser.RandomUser at 0x1a81441aa50>,
 <randomuser.RandomUser at 0x1a81441aa80>,
 <randomuser.RandomUser at 0x1a81441aab0>,
 <randomuser.RandomUser at 0x1a81441aae0>,
 <randomuser.RandomUser at 0x1a81441ab10>,
 <randomuser.RandomUser at 0x1a81441ab40>,
 <randomuser.RandomUser at 0x1a81441ab70>,
 <randomuser.RandomUser at 0x1a81441aba0>,
 <randomuser.RandomUser at 0x1a81441abd0>,
 <randomuser.RandomUser at 0x1a81441ac00>,
 <randomuser.RandomUser at 0x1a81441ac30>,
 <randomuser.RandomUser at 0x1a81441ac60>,
 <randomuser.RandomUser at 0x1a81441ac90>,
 <randomuser.RandomUser at 0x1a81441acc0>,
 <randomuser.RandomUser at 0x1a81441acf0>,
 <randomuser.RandomUser at 0x1a81441ad20>,
 <randomuser.RandomUser at 0x1a81441ad50>,
 <randomuser.RandomUser at 0x1a81441ad80>,
 <randomuser.RandomUser at 0x1a81441adb0>,
 <randomuser.RandomUser at 0x1a81441ade0>,
 <randomuser.RandomUser at 0x1a81441ae10>,
 <randomuser.RandomUser at 0x1a81441ae40>,
 <randomuser.RandomUser at 0x1a81441ae70>,
 <randomuser.RandomUser at 0x1a81441aea0>,
 <randomuser.RandomUser at 0x1a81441aed0>,
 <randomuser.RandomUser at 0x1a81441af00>,
 <randomuser.RandomUser at 0x1a81441af30>,
 <randomuser.RandomUser at 0x1a81441af60>,
 <randomuser.RandomUser at 0x1a81441af90>,
 <randomuser.RandomUser at 0x1a81441afc0>,
 <randomuser.RandomUser at 0x1a81441aff0>,
 <randomuser.RandomUser at 0x1a81441b020>,
 <randomuser.RandomUser at 0x1a81441b050>,
 <randomuser.RandomUser at 0x1a81441b080>,
 <randomuser.RandomUser at 0x1a81441b0b0>,
 <randomuser.RandomUser at 0x1a81441b0e0>,
 <randomuser.RandomUser at 0x1a81441b110>,
 <randomuser.RandomUser at 0x1a81441b140>,
 <randomuser.RandomUser at 0x1a81441b170>,
 <randomuser.RandomUser at 0x1a81441b1a0>,
 <randomuser.RandomUser at 0x1a81441b1d0>,
 <randomuser.RandomUser at 0x1a81441b200>,
 <randomuser.RandomUser at 0x1a81441b230>,
 <randomuser.RandomUser at 0x1a81441b260>,
 <randomuser.RandomUser at 0x1a81441b290>,
 <randomuser.RandomUser at 0x1a81441b2c0>,
 <randomuser.RandomUser at 0x1a81441b2f0>,
 <randomuser.RandomUser at 0x1a81441b320>,
 <randomuser.RandomUser at 0x1a81441b350>,
 <randomuser.RandomUser at 0x1a81441b380>,
 <randomuser.RandomUser at 0x1a81441b3b0>,
 <randomuser.RandomUser at 0x1a81441b3e0>,
 <randomuser.RandomUser at 0x1a81441b410>,
 <randomuser.RandomUser at 0x1a81441b440>,
 <randomuser.RandomUser at 0x1a81441b470>,
 <randomuser.RandomUser at 0x1a81441b4a0>,
 <randomuser.RandomUser at 0x1a81441b4d0>,
 <randomuser.RandomUser at 0x1a81441b500>,
 <randomuser.RandomUser at 0x1a81441b530>,
 <randomuser.RandomUser at 0x1a81441b560>,
 <randomuser.RandomUser at 0x1a81441b590>,
 <randomuser.RandomUser at 0x1a81441b5c0>,
 <randomuser.RandomUser at 0x1a81441b5f0>,
 <randomuser.RandomUser at 0x1a81441b620>,
 <randomuser.RandomUser at 0x1a81441b650>,
 <randomuser.RandomUser at 0x1a81441b680>,
 <randomuser.RandomUser at 0x1a81441b6b0>,
 <randomuser.RandomUser at 0x1a81441b6e0>,
 <randomuser.RandomUser at 0x1a81441b710>,
 <randomuser.RandomUser at 0x1a81441b740>,
 <randomuser.RandomUser at 0x1a81441b770>,
 <randomuser.RandomUser at 0x1a81441b7a0>,
 <randomuser.RandomUser at 0x1a81441b7d0>,
 <randomuser.RandomUser at 0x1a81441b800>,
 <randomuser.RandomUser at 0x1a81441b830>,
 <randomuser.RandomUser at 0x1a81441b860>,
 <randomuser.RandomUser at 0x1a81441b890>,
 <randomuser.RandomUser at 0x1a81441b8c0>,
 <randomuser.RandomUser at 0x1a81441b8f0>,
 <randomuser.RandomUser at 0x1a81441b920>,
 <randomuser.RandomUser at 0x1a81441b950>,
 <randomuser.RandomUser at 0x1a81441b980>,
 <randomuser.RandomUser at 0x1a81441b9b0>,
 <randomuser.RandomUser at 0x1a81441b9e0>,
 <randomuser.RandomUser at 0x1a81441ba10>,
 <randomuser.RandomUser at 0x1a81441ba40>,
 <randomuser.RandomUser at 0x1a81441ba70>,
 <randomuser.RandomUser at 0x1a81441baa0>,
 <randomuser.RandomUser at 0x1a81441bad0>,
 <randomuser.RandomUser at 0x1a81441bb00>,
 <randomuser.RandomUser at 0x1a81441bb30>,
 <randomuser.RandomUser at 0x1a81441bb60>,
 <randomuser.RandomUser at 0x1a81441bb90>,
 <randomuser.RandomUser at 0x1a81441bbc0>,
 <randomuser.RandomUser at 0x1a81441bbf0>,
 <randomuser.RandomUser at 0x1a81441bc20>,
 <randomuser.RandomUser at 0x1a81441bc50>,
 <randomuser.RandomUser at 0x1a81441bc80>,
 <randomuser.RandomUser at 0x1a81441bcb0>,
 <randomuser.RandomUser at 0x1a81441bce0>,
 <randomuser.RandomUser at 0x1a81441bd10>,
 <randomuser.RandomUser at 0x1a81441bd40>,
 <randomuser.RandomUser at 0x1a81441bd70>,
 <randomuser.RandomUser at 0x1a81441bda0>,
 <randomuser.RandomUser at 0x1a81441bdd0>,
 <randomuser.RandomUser at 0x1a81441be00>,
 <randomuser.RandomUser at 0x1a81441be30>,
 <randomuser.RandomUser at 0x1a81441be60>,
 <randomuser.RandomUser at 0x1a81441be90>,
 <randomuser.RandomUser at 0x1a81441bec0>,
 <randomuser.RandomUser at 0x1a81441bef0>,
 <randomuser.RandomUser at 0x1a81441bf20>,
 <randomuser.RandomUser at 0x1a81441bf50>,
 <randomuser.RandomUser at 0x1a81441bf80>,
 <randomuser.RandomUser at 0x1a81441bfb0>,
 <randomuser.RandomUser at 0x1a81441bfe0>,
 <randomuser.RandomUser at 0x1a814430050>,
 <randomuser.RandomUser at 0x1a814430080>,
 <randomuser.RandomUser at 0x1a8144300b0>,
 <randomuser.RandomUser at 0x1a8144300e0>,
 <randomuser.RandomUser at 0x1a814430110>,
 <randomuser.RandomUser at 0x1a814430140>,
 <randomuser.RandomUser at 0x1a814430170>,
 <randomuser.RandomUser at 0x1a8144301a0>,
 <randomuser.RandomUser at 0x1a8144301d0>,
 <randomuser.RandomUser at 0x1a814430200>,
 <randomuser.RandomUser at 0x1a814430230>,
 <randomuser.RandomUser at 0x1a814430260>,
 <randomuser.RandomUser at 0x1a814430290>,
 <randomuser.RandomUser at 0x1a8144302c0>,
 <randomuser.RandomUser at 0x1a8144302f0>,
 <randomuser.RandomUser at 0x1a814430320>,
 <randomuser.RandomUser at 0x1a814430350>,
 <randomuser.RandomUser at 0x1a814430380>,
 <randomuser.RandomUser at 0x1a8144303b0>,
 <randomuser.RandomUser at 0x1a8144303e0>,
 <randomuser.RandomUser at 0x1a814430410>,
 <randomuser.RandomUser at 0x1a814430440>,
 <randomuser.RandomUser at 0x1a814430470>,
 <randomuser.RandomUser at 0x1a8144304a0>,
 <randomuser.RandomUser at 0x1a8144304d0>,
 <randomuser.RandomUser at 0x1a814430500>,
 <randomuser.RandomUser at 0x1a814430530>,
 <randomuser.RandomUser at 0x1a814430560>,
 <randomuser.RandomUser at 0x1a814430590>,
 <randomuser.RandomUser at 0x1a8144305c0>,
 <randomuser.RandomUser at 0x1a8144305f0>,
 <randomuser.RandomUser at 0x1a814430620>,
 <randomuser.RandomUser at 0x1a814430650>,
 <randomuser.RandomUser at 0x1a814430680>,
 <randomuser.RandomUser at 0x1a8144306b0>,
 <randomuser.RandomUser at 0x1a8144306e0>,
 <randomuser.RandomUser at 0x1a814430710>,
 <randomuser.RandomUser at 0x1a814430740>,
 <randomuser.RandomUser at 0x1a814430770>,

In [28]:
name = r.get_full_name()

In [32]:
for city in users:
    print(city.get_city())

Kastamonu
Wells
Meterik
Vitória de Santo Antão
Zaragoza
Tourcoing
Versailles
Tuam
Rancho Cucamonga
Clonmel
Dublin
Leppävirta
Nevşehir
Quarten
Artvin
Nowra
Toholampi
Kastamonu
St. George
Waco
San Sebastián de Los Reyes
Palmerston North
Norderney
Geithus
Karaman
Angers
Leixlip
Pozuelo de Alarcón
Oulunsalo
Donneloye
Paltamo
Shannon
Bayburt
ساری
Hospitalet de Llobregat
بندرعباس
Alcalá de Henares
Masterton
Stevenage
Perpignan
Roosteren
Newbridge
Hampstead
Montpellier
Juelsminde
Santander
Caen
Farmers Branch
Hortolândia
Tralee
Elche
Corban
Meldal
Joutsa
Maynooth
Santa Cruz de Tenerife
Dillenburg
Dungarvan
Zwönitz
Edinburgh
Fauquier
Roslev
São Luís
Vaala
Malahide
Castellón de la Plana
St. George
Raahe
Wellington
Napier
Gjerlev
Perpignan
دزفول
Isparta
Swansea
Naas
Nampa
Plymouth
Kalgoorlie
Aix-En-Provence
Nieuwe Krim
Goedereede
Córdoba
Bartın
Wolframs-Eschenbach
South Valley
Nampa
Mäntyharju
Simi Valley
Londonderry
Turgi
سبزوار
قم
Mulhouse
Oakville
Steinkjer
Castellón de la Plana
تهران
Balneário Camboriú
Upper Hutt
Auckland
Fürstenberg/Havel
Torrejón de Ardoz
Viitasaari
Schriesheim
Bolu
Wijdenes
پاکدشت
Kongsvinger
Vigo
Durham
Kotka
Bartın
Australian Capital Territory
Castellón de la Plana
Mullingar
Burgos
Warragul
Plymouth
Herbaijum
Buncrana
Lyon
Maitland
Fauquier
Lyon
Red Bluff
Caucaia
Rueil-Malmaison
سبزوار
Maynooth
Grand Rapids
Rochester
Kouvola
Rusko
Lichfield
Rotorua
Niederönz
Rotorua
Attiswil
Charlottetown
Espoo
Tunceli
Kiiminki
Ubá
Ballina
Dettelbach
Karvia
Heinola
Thurles
Málaga
Palma de Mallorca
Athenry
Westminster
København S
Invercargill
Sullens
Uzwil
Wellington
Oberweningen
Papekop
Innfjorden
Salem
Århus C.
Hausjärvi
Eede Zld
Coffs Harbour
Leimen
Punkaharju
Gloucester
گلستان
Talavera de la Reina
ارومیه
Steinburg
Van
قم
Assens
Geelong
Bekkjarvik
Jasper
Allmendingen
Beder
Champigny-sur-Marne
Birigüi
Manger
خمینی‌شهر
Erzincan
Piracicaba
Manchester
Syracuse
Ely
Gandía
Cape Coral
Trostberg
Baar
Oulunsalo
Durham
Gisborne
شیراز
Newport
Bordeaux
Hereford
Geeuwenbrug
Ottersøy
Villeurbanne
Aracaju
Lille
Dörflingen
Rouen
Snertinge
Swansea
Blenheim
Lincoln
Høyjord
Bristol
Greystones
Kalgoorlie
Vallejo
Vitoria
Jyväskylä
Santander
Hemrik
Vesanto
Souris
Perth
Konglungen
Teuva
Lavia
Le Havre
Bühl
Trimmis
Roedovre
کاشان
Birsfelden
Magdeburg
Sherbrooke
Sinop
Frederiksberg
Vieremä
Vitoria
Tuam
V.Skerninge
Pontevedra
Youghal
Rouen
Hastings
تبریز
Athy
Darwin
Port Macquarie
Sommersted
Patos de Minas
بوشهر
Torrevieja
Westport
Mitterteich
Kannonkoski
Chester
Birr
Parkano
Lusk
Boppelsen
Snertinge
Portlaoise
Mildura
Giessenlanden
Lindow (Mark)
Øyslebø
Kırıkkale
Rottum Fr
Kilcoole
Drogheda
Movik
Jasper
Amiens
Isparta
Santiago de Compostela
Carapicuíba
Cachoeiro de Itapemirim
Isojoki
Nij Beets
Randers Nø
آبادان
Kollumerzwaag
Gladstone
Alcobendas
Birmingham
Surprise
بیرجند
Trout Lake
Sirevåg
Wilhelminaoord
Caen
Klokkarstua
Konya
Revetal
Lumsden
Rio de Janeiro
Peitz
Steendam
خوی
Sysmä
Cairns
Kaavi
Modesto
Hakkâri
Salisbury
Kiel
Arvada
São Caetano do Sul
Viby Sj.
Verdalsøra
Kirtorf
Almería
بوشهر
Santarém
Ferrol
Pamplona
Nordkisa
Beaumont
Athenry
San Sebastián
Eidsvik
Sydney
Såstadbråten
Mesquita
New Ross
Chelsea
Argenteuil
Auckland
Wiesmoor
Raerd
Providence
Alexandria
Vernon
Henniez
Portlaoise
گلستان
Berching
Adıyaman
Nelson
Adelaide
قزوین
Santander
Monaghan
Ankara
Marseille
Caen
Elazığ
Oosterbeek
Wasungen
Derby
Lumsden
Sallins
Kyyjärvi
Strijensas
Sortland
Barcelona
Vantaa
Urnäsch
Guarapari
Blessington
Naas
Eidfjord
Beek-Ubbergen
Lages
Swansea
دزفول
Santa Luzia
Vila Velha
Fuenlabrada
Wellington
Portsmouth
Dundee
بجنورد
Mallow
Vitória
Ottersbo
خرم‌آباد
Leutenberg
Øster Assels
Outokumpu
Minto
Wollongong
Pedersöre
Tweed
Perho
Bovensmilde
Broekhuizenvorst
Adelaide
Fischenthal
Praia Grande
Bath
Londonderry
Vinkega
Mildura
Darwin
Napier
Talavera de la Reina
Tauranga
Lincoln
Kvistgaard
Bontebok
Kristinestad
Schrozberg
Geraldton
Hamilton
Wollongong
Haslev
Hailuoto
بروجرد
Risør
Lintrup
Bandon
Elizabeth
Kesselt
Lusk
Logroño
Obfelden
Toulon
مشهد
Sheffield
Lauchhammer
Konya
Carrigtwohill
Bayburt
Aydın
Gandía
Vigo
Strasbourg
Longford
Chester
Norfolk
City of London
Balıkesir
اراک
Gais
Leeds
Roubaix
Bath
Provence
Miehikkälä
Mildura
Shepparton
Carlisle
Mulhouse
Århus C.
اهواز
Brest
Åmot
Antalya
Melbourne
Haslev
Aulnay-sous-Bois
Macapá
Shepparton
Wagga Wagga
Maitland
Kangasala
Toledo
Stallikon
San Sebastián
Rouen
Coffs Harbour
Aksaray
Rio das Ostras
کرج
Navan
Damwald
Maracanaú
Neresheim
Trim
Namdalseid
Poços de Caldas
Muş
Rio Grande
Somero
Carrick-on-Suir
Balıkesir
Winchester
Burgstädt
Torrejón de Ardoz
Mildura
Peterborough
Niedergösgen
Fountainbleu
Hamilton
اصفهان
Russell
Tweed
Waalre
Masterton
Ardee
Sander
Nancy
Brest
Castellón de la Plana
Aulnay-sous-Bois
Valencia
Hospitalet de Llobregat
Exeter
Pregny-Chambésy
کرمانشاه
Exeter
Ølstykke
Nieuweroord
Shiloh
Bopfingen
Melle
Inverness
Bath
Mesquite
Itapipoca
Maranguape
Argenteuil
Manisa
Ilhéus
تبریز
Bilecik
Kastamonu
Grenoble
Viby J.
Jerez de la Frontera
Angra dos Reis
Parla
Porirua
Roedovre
Castlebar
بندرعباس
Harderwijk
Kvaløysletta
Burdaard
Rääkkylä
Itapevi
Torvik
Newport
Darwin
New Plymouth
Exeter
ایلام
Grandevent
Masterton
Magé
Waldshut
Castellón de la Plana
Perpignan
Stoke-on-Trent
Gouda
New Plymouth
Santos
Americana
Elsfleth
Pamplona
Overbetuwe
Port Macquarie
Kırşehir
Hobart
Jasper
Balsthal
Stevenage
Gørløse
Bolu
Governador Valadares
Kinsealy-Drinan
Nykøbing F
Pyhäranta
Athenry
Kütahya
کرمان
Celbridge
Warffum
Fort Wayne
Las Vegas
Greystones
Skreia
Laichingen
Montes Claros
Tauranga
Vitoria
Providence
San Sebastián de Los Reyes
Vitória
Sunderland
Vaala
La Palma
Duisburg
Georgetown
Rize
Nummi
Langenfeld (Rheinland)
Breedenbroek
The Colony
Snertinge
Brekkeåsen
Rio Grande
Siikajoki
Bendigo
Notre Dame de Lourdes
Parkano
Taupo
Østhusvik
St.Merløse
Mühledorf (Be)
Longford
Saltum
Olathe
Alicante
Blenheim
Magé
Noerre Alslev
Princeton
Murrieta
Eemdijk
Blessington
Pontevedra
Saarlouis
Kleppe
Hamilton
Murcia
Kent
Drogheda
Feda
Skaerbaek
Wexford
Denekamp
Tokat
Bayburt
Sundby/Erslev
Leipziger Land
Killeen
Ådalsbruk
Fountainbleu
Saint Paul
Hurup Thy
Toulon
Clos du Doubs
Russell
Bussy-Chardonney
Sandy Lake
Bartın
Marseille
Närpes
Karaman
Burdur
Torrente
Sinop
Rüdtligen-Alchenflüh
La Baroche
Argerskov
Elspeet
Parkano
Warragul
Uruguaiana
Bathurst
Klitmøller
Osasco
Herzogenaurach
Punkaharju
Cairns
Bowral
Auckland
Råkvågen
Ballinasloe
Timaru
El Paso
Ulsted, Hals
Belmont
Risch
Ilomantsi
Straumgjerde
Burdur
Seinäjoki
Zwieselberg
Århus C.
Jacareí
Tokat
Kil
Kalgoorlie
Mogi das Cruzes
Dunedin
Palmerston North
Metz
Oakville
Sheffield
Nokia
Uurainen
Yozgat
Offenbach am Main
Gasselternijveenschemond
Oldenzijl
Böblingen
Pomarkku
Rush
Peterborough
Créteil
Hansnes
Berger
Rauma
Toholampi
اردبیل
Fluitenberg
Elazığ
Waldbröl
Coffs Harbour
Denizli
Pozuelo de Alarcón
Santa Cruz de Tenerife
Port Macquarie
Omaha
یزد
Stenderup
Metz
Edinburgh
نیشابور
Innfjorden
Passage West
Liverpool
Evijärvi
Sønder Stenderup
Närpes
Holthees
Meerssen
Kayseri
Ripon
Irvine
Büetigen
Hervey Bay
Winsum
Garden Grove
Clermont-Ferrand
Taunusstein
Naila
Kansas City
Blaubeuren
Ballinasloe
Sirevåg
Rio de Janeiro
شهریار
Boston
Niederkassel
Trenton
Bergen Nh
Selm
Kayseri
Roedovre
Allmendingen
Kelbra (Kyffhäuser)
Rickenbach (So)
Mullingar
Delisle
Lenzen
Timaru
Vendlincourt
Egmond-Binnen
Imatra
Hattula
Albacete
Lasalle
Grand Falls
Geraldton
Fort-de-France
Cornwall
Eskişehir
Aix-En-Provence
Svøo
Marseille
Tauranga
Klitmøller
Davenport
Thörigen
Etenaken
Rosenheim
Twijzel
Schortens
Edirne
Carrick-on-Suir
Balıkesir
Løten
Palmerston North
Carrickmacross
Aarhus N
St Davids
Lloydminster
Greymouth
Princeton
مشهد
Lauchheim
Port-Valais
Kells
Tinte
Kırklareli
ملارد
Exeter
Everett
Riihem
Brøndby Strand
Nilópolis
Providence
Gorey
Nebikon
Castellón de la Plana
Noordeloos
Pontevedra
Skoge
Aix-En-Provence
Townsville
Ellingen
اسلام‌شهر
Clavaleyres
Emsdetten
Trenton
Jaboatão dos Guararapes
Codó
Warragul
Liverpool
Killarney
Midleton
Batnfjordsøra
Belmont
Gemert-Bakel
Evenskjær
نجف‌آباد
Østenstad
Aubervilliers
Bathurst
Immenhausen
Baard
Trout Lake
Brest
Wollongong
خرم‌آباد
مشهد
Greymouth
Chichester
Dunedin
Sherbrooke
Aydın
New Ross
Oxnard
Chula Vista
Pello
Taupo
Nelson
Melbourne
Angers
Saint-Denis
Zonguldak
Toulouse
Sinop
Lichfield
Hovin
Penthalaz
کرج
Merishausen
Argenteuil
Ciudad Real
Reims
Stirling
Nottingham
تهران
Dijon
Bathurst
Santander
ساری
Hirtsals
Loimaa
Årnes
Tampere
Skjold
Australian Capital Territory
Penthaz
Marabá
Sørvad
Göttingen
Jerslev Sj
Biest-Houtakker
Mosvik
Plauen
Amasya
شهریار
بجنورد
Gladstad
Victorville
Russell
دزفول
Lages
Gümüşhane
Lille
Bundaberg
Roseville
Timaru
Peperga
Adelaide
Waterloo
Belmont
Gjerlev
Denton
زاهدان
Piracicaba
قرچک
Serra
Eibenstock
Orense
Årnes
Steggerda
Hamilton
Balıkesir
Upper Hutt
Grand Falls
Indaiatuba
ارومیه
Whangarei
Nykøbing F
Balbriggan
Kyyjärvi
Ananindeua
Sutton
Castlebar
Atibaia
Dijon
Wellington
Whanganui
Orihuela
Klitmøller
Peterborough
Schüpfen
Birr
Devonport
ایلام
Devonport
Auckland
Grenoble
Rouen
New Plymouth
Atlanta
Kindelbrück
تبریز
Fiez
Bad Bergzabern
Belfast
کرمانشاه
خمینی‌شهر
Brusque
Halden
گلستان
Montreuil
Şırnak
Moosleerau
Kalgoorlie
Furtwangen im Schwarzwald
خرم‌آباد
Taupo
Bunbury
Rotorua
Muğla
Bilbao
Blumenau
Aaborg Øst
Dunkerque
Arbaz
Lower Hutt
New Glasgow
Burgos
Concord
Melbourne
Chester
Oulu
Hobart
Mallow
Nantes
Darwin
Kaarst
Carrick-on-Shannon
Sandved
Falera
Gasselterboerveen
Bad Brückenau
Luhanka
Dunkerque
Perpignan
Masterton
خوی
Tours
Sommeri
Campina Grande
Lütisburg
Rockhampton
Ruokolahti
Brest
Upper Hutt
Vitoria
Vaulruz
Magé
Derby
Centennial
Havelock
Joppe
Hirtsals
دزفول
Brisbane
Palma de Mallorca

In [33]:
for user in users:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/96.jpg
https://randomuser.me/api/portraits/men/83.jpg
https://randomuser.me/api/portraits/men/29.jpg
https://randomuser.me/api/portraits/women/94.jpg
https://randomuser.me/api/portraits/women/73.jpg
https://randomuser.me/api/portraits/men/72.jpg
https://randomuser.me/api/portraits/men/47.jpg
https://randomuser.me/api/portraits/women/44.jpg
https://randomuser.me/api/portraits/women/16.jpg
https://randomuser.me/api/portraits/women/50.jpg
https://randomuser.me/api/portraits/women/25.jpg
https://randomuser.me/api/portraits/men/56.jpg
https://randomuser.me/api/portraits/men/68.jpg
https://randomuser.me/api/portraits/women/0.jpg
https://randomuser.me/api/portraits/women/74.jpg
https://randomuser.me/api/portraits/men/91.jpg
https://randomuser.me/api/portraits/men/82.jpg
https://randomuser.me/api/portraits/men/32.jpg
https://randomuser.me/api/portraits/women/49.jpg
https://randomuser.me/api/portraits/men/81.jpg
https://randomuser.me/api/portraits/men/19.jpg
https://randomuser.me/api/portraits/women/26.jpg
https://randomuser.me/api/portraits/women/19.jpg
https://randomuser.me/api/portraits/men/17.jpg
https://randomuser.me/api/portraits/men/3.jpg
https://randomuser.me/api/portraits/men/74.jpg
https://randomuser.me/api/portraits/women/72.jpg
https://randomuser.me/api/portraits/men/22.jpg
https://randomuser.me/api/portraits/women/12.jpg
https://randomuser.me/api/portraits/women/17.jpg
https://randomuser.me/api/portraits/women/61.jpg
https://randomuser.me/api/portraits/women/80.jpg
https://randomuser.me/api/portraits/women/89.jpg
https://randomuser.me/api/portraits/women/83.jpg
https://randomuser.me/api/portraits/women/89.jpg
https://randomuser.me/api/portraits/men/66.jpg
https://randomuser.me/api/portraits/men/61.jpg
https://randomuser.me/api/portraits/women/43.jpg
https://randomuser.me/api/portraits/women/92.jpg
https://randomuser.me/api/portraits/men/95.jpg
https://randomuser.me/api/portraits/women/31.jpg
https://randomuser.me/api/portraits/women/29.jpg
https://randomuser.me/api/portraits/men/85.jpg
https://randomuser.me/api/portraits/men/46.jpg
https://randomuser.me/api/portraits/men/56.jpg
https://randomuser.me/api/portraits/men/75.jpg
https://randomuser.me/api/portraits/women/12.jpg
https://randomuser.me/api/portraits/men/82.jpg
https://randomuser.me/api/portraits/men/92.jpg
https://randomuser.me/api/portraits/women/16.jpg
https://randomuser.me/api/portraits/men/17.jpg
https://randomuser.me/api/portraits/men/91.jpg
https://randomuser.me/api/portraits/men/9.jpg
https://randomuser.me/api/portraits/women/10.jpg
https://randomuser.me/api/portraits/men/41.jpg
https://randomuser.me/api/portraits/women/16.jpg
https://randomuser.me/api/portraits/men/6.jpg
https://randomuser.me/api/portraits/women/53.jpg
https://randomuser.me/api/portraits/men/2.jpg
https://randomuser.me/api/portraits/men/14.jpg
https://randomuser.me/api/portraits/women/40.jpg
https://randomuser.me/api/portraits/men/41.jpg
https://randomuser.me/api/portraits/women/88.jpg
https://randomuser.me/api/portraits/women/88.jpg
https://randomuser.me/api/portraits/women/87.jpg
https://randomuser.me/api/portraits/women/51.jpg
https://randomuser.me/api/portraits/women/57.jpg
https://randomuser.me/api/portraits/men/36.jpg
https://randomuser.me/api/portraits/women/21.jpg
https://randomuser.me/api/portraits/women/24.jpg
https://randomuser.me/api/portraits/men/61.jpg
https://randomuser.me/api/portraits/women/58.jpg
https://randomuser.me/api/portraits/women/69.jpg
https://randomuser.me/api/portraits/men/20.jpg
https://randomuser.me/api/portraits/women/91.jpg
https://randomuser.me/api/portraits/men/48.jpg
https://randomuser.me/api/portraits/men/0.jpg
https://randomuser.me/api/portraits/women/11.jpg
https://randomuser.me/api/portraits/women/85.jpg
https://randomuser.me/api/portraits/men/90.jpg
https://randomuser.me/api/portraits/women/26.jpg
https://randomuser.me/api/portraits/men/75.jpg
https://randomuser.me/api/portraits/men/18.jpg
https://randomuser.me/api/portraits/men/92.jpg
https://randomuser.me/api/portraits/women/47.jpg
https://randomuser.me/api/portraits/men/67.jpg
https://randomuser.me/api/portraits/men/33.jpg
https://randomuser.me/api/portraits/men/55.jpg
https://randomuser.me/api/portraits/men/19.jpg
https://randomuser.me/api/portraits/men/59.jpg
https://randomuser.me/api/portraits/men/63.jpg
https://randomuser.me/api/portraits/men/53.jpg
https://randomuser.me/api/portraits/women/30.jpg
https://randomuser.me/api/portraits/women/51.jpg
https://randomuser.me/api/portraits/women/89.jpg
https://randomuser.me/api/portraits/women/92.jpg
https://randomuser.me/api/portraits/women/88.jpg
https://randomuser.me/api/portraits/men/28.jpg
https://randomuser.me/api/portraits/men/77.jpg
https://randomuser.me/api/portraits/women/34.jpg
https://randomuser.me/api/portraits/men/56.jpg
https://randomuser.me/api/portraits/men/9.jpg
https://randomuser.me/api/portraits/men/0.jpg
https://randomuser.me/api/portraits/women/65.jpg
https://randomuser.me/api/portraits/women/94.jpg
https://randomuser.me/api/portraits/men/83.jpg
https://randomuser.me/api/portraits/men/20.jpg
https://randomuser.me/api/portraits/men/96.jpg
https://randomuser.me/api/portraits/men/2.jpg
https://randomuser.me/api/portraits/women/39.jpg
https://randomuser.me/api/portraits/men/83.jpg
https://randomuser.me/api/portraits/men/69.jpg
https://randomuser.me/api/portraits/men/28.jpg
https://randomuser.me/api/portraits/men/60.jpg
https://randomuser.me/api/portraits/men/40.jpg
https://randomuser.me/api/portraits/men/24.jpg
https://randomuser.me/api/portraits/women/76.jpg
https://randomuser.me/api/portraits/women/60.jpg
https://randomuser.me/api/portraits/men/43.jpg
https://randomuser.me/api/portraits/men/76.jpg
https://randomuser.me/api/portraits/women/29.jpg
https://randomuser.me/api/portraits/men/52.jpg
https://randomuser.me/api/portraits/men/90.jpg
https://randomuser.me/api/portraits/men/1.jpg
https://randomuser.me/api/portraits/men/74.jpg
https://randomuser.me/api/portraits/men/85.jpg
https://randomuser.me/api/portraits/men/44.jpg
https://randomuser.me/api/portraits/women/91.jpg
https://randomuser.me/api/portraits/women/41.jpg
https://randomuser.me/api/portraits/men/52.jpg
https://randomuser.me/api/portraits/women/54.jpg
https://randomuser.me/api/portraits/women/26.jpg
https://randomuser.me/api/portraits/men/6.jpg
https://randomuser.me/api/portraits/women/37.jpg
https://randomuser.me/api/portraits/women/1.jpg
https://randomuser.me/api/portraits/men/31.jpg
https://randomuser.me/api/portraits/men/29.jpg
https://randomuser.me/api/portraits/women/0.jpg
https://randomuser.me/api/portraits/women/42.jpg
https://randomuser.me/api/portraits/men/62.jpg
https://randomuser.me/api/portraits/women/33.jpg
https://randomuser.me/api/portraits/women/50.jpg
https://randomuser.me/api/portraits/women/29.jpg
https://randomuser.me/api/portraits/women/92.jpg
https://randomuser.me/api/portraits/men/54.jpg
https://randomuser.me/api/portraits/men/83.jpg
https://randomuser.me/api/portraits/women/58.jpg
https://randomuser.me/api/portraits/women/42.jpg
https://randomuser.me/api/portraits/men/66.jpg
https://randomuser.me/api/portraits/men/34.jpg
https://randomuser.me/api/portraits/women/91.jpg
https://randomuser.me/api/portraits/women/70.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/women/59.jpg
https://randomuser.me/api/portraits/women/87.jpg
https://randomuser.me/api/portraits/men/79.jpg
https://randomuser.me/api/portraits/men/62.jpg
https://randomuser.me/api/portraits/men/86.jpg
https://randomuser.me/api/portraits/men/94.jpg
https://randomuser.me/api/portraits/women/37.jpg
https://randomuser.me/api/portraits/men/37.jpg
https://randomuser.me/api/portraits/men/9.jpg
https://randomuser.me/api/portraits/women/27.jpg
https://randomuser.me/api/portraits/men/31.jpg
https://randomuser.me/api/portraits/women/96.jpg
https://randomuser.me/api/portraits/men/64.jpg
https://randomuser.me/api/portraits/women/50.jpg
https://randomuser.me/api/portraits/women/44.jpg
https://randomuser.me/api/portraits/men/52.jpg
https://randomuser.me/api/portraits/men/74.jpg
https://randomuser.me/api/portraits/men/14.jpg
https://randomuser.me/api/portraits/women/68.jpg
https://randomuser.me/api/portraits/women/92.jpg
https://randomuser.me/api/portraits/women/55.jpg
https://randomuser.me/api/portraits/men/55.jpg
https://randomuser.me/api/portraits/men/24.jpg
https://randomuser.me/api/portraits/women/54.jpg
https://randomuser.me/api/portraits/women/45.jpg
https://randomuser.me/api/portraits/women/31.jpg
https://randomuser.me/api/portraits/men/19.jpg
https://randomuser.me/api/portraits/men/92.jpg
https://randomuser.me/api/portraits/women/14.jpg
https://randomuser.me/api/portraits/women/70.jpg
https://randomuser.me/api/portraits/men/72.jpg
https://randomuser.me/api/portraits/men/60.jpg
https://randomuser.me/api/portraits/men/2.jpg
https://randomuser.me/api/portraits/women/47.jpg
https://randomuser.me/api/portraits/women/52.jpg
https://randomuser.me/api/portraits/men/7.jpg
https://randomuser.me/api/portraits/women/25.jpg
https://randomuser.me/api/portraits/men/79.jpg
https://randomuser.me/api/portraits/men/99.jpg
https://randomuser.me/api/portraits/women/54.jpg
https://randomuser.me/api/portraits/women/87.jpg
https://randomuser.me/api/portraits/men/53.jpg
https://randomuser.me/api/portraits/men/16.jpg
https://randomuser.me/api/portraits/men/2.jpg
https://randomuser.me/api/portraits/men/41.jpg
https://randomuser.me/api/portraits/women/79.jpg
https://randomuser.me/api/portraits/men/4.jpg
https://randomuser.me/api/portraits/women/14.jpg
https://randomuser.me/api/portraits/men/54.jpg
https://randomuser.me/api/portraits/men/74.jpg
https://randomuser.me/api/portraits/men/7.jpg
https://randomuser.me/api/portraits/men/82.jpg
https://randomuser.me/api/portraits/men/66.jpg
https://randomuser.me/api/portraits/men/88.jpg
https://randomuser.me/api/portraits/men/6.jpg
https://randomuser.me/api/portraits/women/91.jpg
https://randomuser.me/api/portraits/men/28.jpg
https://randomuser.me/api/portraits/men/22.jpg
https://randomuser.me/api/portraits/women/13.jpg
https://randomuser.me/api/portraits/men/60.jpg
https://randomuser.me/api/portraits/women/82.jpg
https://randomuser.me/api/portraits/men/35.jpg
https://randomuser.me/api/portraits/women/24.jpg
https://randomuser.me/api/portraits/women/66.jpg
https://randomuser.me/api/portraits/men/40.jpg
https://randomuser.me/api/portraits/women/63.jpg
https://randomuser.me/api/portraits/men/47.jpg
https://randomuser.me/api/portraits/women/37.jpg
https://randomuser.me/api/portraits/women/49.jpg
https://randomuser.me/api/portraits/men/48.jpg
https://randomuser.me/api/portraits/men/15.jpg
https://randomuser.me/api/portraits/men/87.jpg
https://randomuser.me/api/portraits/men/35.jpg
https://randomuser.me/api/portraits/men/44.jpg
https://randomuser.me/api/portraits/men/83.jpg
https://randomuser.me/api/portraits/women/3.jpg
https://randomuser.me/api/portraits/men/4.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/women/4.jpg
https://randomuser.me/api/portraits/women/64.jpg
https://randomuser.me/api/portraits/men/52.jpg
https://randomuser.me/api/portraits/men/45.jpg
https://randomuser.me/api/portraits/men/36.jpg
https://randomuser.me/api/portraits/men/0.jpg
https://randomuser.me/api/portraits/women/27.jpg
https://randomuser.me/api/portraits/men/99.jpg
https://randomuser.me/api/portraits/women/94.jpg
https://randomuser.me/api/portraits/women/23.jpg
https://randomuser.me/api/portraits/men/12.jpg
https://randomuser.me/api/portraits/men/45.jpg
https://randomuser.me/api/portraits/women/45.jpg
https://randomuser.me/api/portraits/men/57.jpg
https://randomuser.me/api/portraits/women/80.jpg
https://randomuser.me/api/portraits/men/0.jpg
https://randomuser.me/api/portraits/men/11.jpg
https://randomuser.me/api/portraits/women/26.jpg
https://randomuser.me/api/portraits/women/11.jpg
https://randomuser.me/api/portraits/men/63.jpg
https://randomuser.me/api/portraits/men/51.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/women/32.jpg
https://randomuser.me/api/portraits/women/72.jpg
https://randomuser.me/api/portraits/men/51.jpg
https://randomuser.me/api/portraits/men/45.jpg
https://randomuser.me/api/portraits/men/0.jpg
https://randomuser.me/api/portraits/men/52.jpg
https://randomuser.me/api/portraits/women/58.jpg
https://randomuser.me/api/portraits/men/36.jpg
https://randomuser.me/api/portraits/women/2.jpg
https://randomuser.me/api/portraits/men/86.jpg
https://randomuser.me/api/portraits/men/22.jpg
https://randomuser.me/api/portraits/men/96.jpg
https://randomuser.me/api/portraits/men/44.jpg
https://randomuser.me/api/portraits/women/0.jpg
https://randomuser.me/api/portraits/women/46.jpg
https://randomuser.me/api/portraits/women/7.jpg
https://randomuser.me/api/portraits/men/41.jpg
https://randomuser.me/api/portraits/women/63.jpg
https://randomuser.me/api/portraits/women/69.jpg
https://randomuser.me/api/portraits/men/2.jpg
https://randomuser.me/api/portraits/women/84.jpg
https://randomuser.me/api/portraits/men/97.jpg
https://randomuser.me/api/portraits/women/93.jpg
https://randomuser.me/api/portraits/women/25.jpg
https://randomuser.me/api/portraits/men/18.jpg
https://randomuser.me/api/portraits/men/29.jpg
https://randomuser.me/api/portraits/women/58.jpg
https://randomuser.me/api/portraits/men/19.jpg
https://randomuser.me/api/portraits/women/84.jpg
https://randomuser.me/api/portraits/men/80.jpg
https://randomuser.me/api/portraits/women/56.jpg
https://randomuser.me/api/portraits/women/49.jpg
https://randomuser.me/api/portraits/men/79.jpg
https://randomuser.me/api/portraits/women/47.jpg
https://randomuser.me/api/portraits/women/77.jpg
https://randomuser.me/api/portraits/women/10.jpg
https://randomuser.me/api/portraits/women/17.jpg
https://randomuser.me/api/portraits/women/24.jpg
https://randomuser.me/api/portraits/women/3.jpg
https://randomuser.me/api/portraits/women/96.jpg
https://randomuser.me/api/portraits/men/9.jpg
https://randomuser.me/api/portraits/women/60.jpg
https://randomuser.me/api/portraits/men/72.jpg
https://randomuser.me/api/portraits/men/94.jpg
https://randomuser.me/api/portraits/women/30.jpg
https://randomuser.me/api/portraits/men/34.jpg
https://randomuser.me/api/portraits/men/75.jpg
https://randomuser.me/api/portraits/women/54.jpg
https://randomuser.me/api/portraits/men/73.jpg
https://randomuser.me/api/portraits/men/46.jpg
https://randomuser.me/api/portraits/men/26.jpg
https://randomuser.me/api/portraits/women/33.jpg
https://randomuser.me/api/portraits/women/64.jpg
https://randomuser.me/api/portraits/men/94.jpg
https://randomuser.me/api/portraits/men/99.jpg
https://randomuser.me/api/portraits/women/8.jpg
https://randomuser.me/api/portraits/women/83.jpg
https://randomuser.me/api/portraits/women/15.jpg
https://randomuser.me/api/portraits/women/65.jpg
https://randomuser.me/api/portraits/men/24.jpg
https://randomuser.me/api/portraits/women/51.jpg
https://randomuser.me/api/portraits/women/93.jpg
https://randomuser.me/api/portraits/women/91.jpg
https://randomuser.me/api/portraits/men/16.jpg
https://randomuser.me/api/portraits/men/14.jpg
https://randomuser.me/api/portraits/men/67.jpg
https://randomuser.me/api/portraits/women/59.jpg
https://randomuser.me/api/portraits/men/58.jpg
https://randomuser.me/api/portraits/women/86.jpg
https://randomuser.me/api/portraits/women/32.jpg
https://randomuser.me/api/portraits/women/13.jpg
https://randomuser.me/api/portraits/men/69.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/women/19.jpg
https://randomuser.me/api/portraits/women/79.jpg
https://randomuser.me/api/portraits/women/35.jpg
https://randomuser.me/api/portraits/women/79.jpg
https://randomuser.me/api/portraits/women/54.jpg
https://randomuser.me/api/portraits/women/19.jpg
https://randomuser.me/api/portraits/women/26.jpg
https://randomuser.me/api/portraits/men/96.jpg
https://randomuser.me/api/portraits/women/29.jpg
https://randomuser.me/api/portraits/women/17.jpg
https://randomuser.me/api/portraits/women/85.jpg
https://randomuser.me/api/portraits/women/88.jpg
https://randomuser.me/api/portraits/women/61.jpg
https://randomuser.me/api/portraits/women/93.jpg
https://randomuser.me/api/portraits/women/21.jpg
https://randomuser.me/api/portraits/women/43.jpg
https://randomuser.me/api/portraits/men/46.jpg
https://randomuser.me/api/portraits/women/80.jpg
https://randomuser.me/api/portraits/women/43.jpg
https://randomuser.me/api/portraits/women/68.jpg
https://randomuser.me/api/portraits/men/81.jpg
https://randomuser.me/api/portraits/women/85.jpg
https://randomuser.me/api/portraits/men/26.jpg
https://randomuser.me/api/portraits/women/66.jpg
https://randomuser.me/api/portraits/women/0.jpg
https://randomuser.me/api/portraits/women/46.jpg
https://randomuser.me/api/portraits/men/27.jpg
https://randomuser.me/api/portraits/women/62.jpg
https://randomuser.me/api/portraits/women/23.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/women/64.jpg
https://randomuser.me/api/portraits/men/60.jpg
https://randomuser.me/api/portraits/men/22.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/men/29.jpg
https://randomuser.me/api/portraits/women/39.jpg
https://randomuser.me/api/portraits/men/3.jpg
https://randomuser.me/api/portraits/men/20.jpg
https://randomuser.me/api/portraits/men/9.jpg
https://randomuser.me/api/portraits/men/3.jpg
https://randomuser.me/api/portraits/men/34.jpg
https://randomuser.me/api/portraits/men/1.jpg
https://randomuser.me/api/portraits/men/65.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/men/77.jpg
https://randomuser.me/api/portraits/men/1.jpg
https://randomuser.me/api/portraits/women/48.jpg
https://randomuser.me/api/portraits/women/56.jpg
https://randomuser.me/api/portraits/men/69.jpg
https://randomuser.me/api/portraits/women/78.jpg
https://randomuser.me/api/portraits/women/87.jpg
https://randomuser.me/api/portraits/women/45.jpg
https://randomuser.me/api/portraits/men/11.jpg
https://randomuser.me/api/portraits/men/98.jpg
https://randomuser.me/api/portraits/men/43.jpg
https://randomuser.me/api/portraits/men/15.jpg
https://randomuser.me/api/portraits/women/62.jpg
https://randomuser.me/api/portraits/men/67.jpg
https://randomuser.me/api/portraits/women/38.jpg
https://randomuser.me/api/portraits/women/72.jpg
https://randomuser.me/api/portraits/women/53.jpg
https://randomuser.me/api/portraits/men/90.jpg
https://randomuser.me/api/portraits/men/65.jpg
https://randomuser.me/api/portraits/women/74.jpg
https://randomuser.me/api/portraits/men/62.jpg
https://randomuser.me/api/portraits/women/76.jpg
https://randomuser.me/api/portraits/men/60.jpg
https://randomuser.me/api/portraits/men/59.jpg
https://randomuser.me/api/portraits/women/57.jpg
https://randomuser.me/api/portraits/women/26.jpg
https://randomuser.me/api/portraits/women/40.jpg
https://randomuser.me/api/portraits/men/56.jpg
https://randomuser.me/api/portraits/men/94.jpg
https://randomuser.me/api/portraits/women/79.jpg
https://randomuser.me/api/portraits/men/36.jpg
https://randomuser.me/api/portraits/women/22.jpg
https://randomuser.me/api/portraits/men/78.jpg
https://randomuser.me/api/portraits/men/27.jpg
https://randomuser.me/api/portraits/men/12.jpg
https://randomuser.me/api/portraits/men/69.jpg
https://randomuser.me/api/portraits/men/89.jpg
https://randomuser.me/api/portraits/men/94.jpg
https://randomuser.me/api/portraits/women/70.jpg
https://randomuser.me/api/portraits/women/13.jpg
https://randomuser.me/api/portraits/women/85.jpg
https://randomuser.me/api/portraits/men/57.jpg
https://randomuser.me/api/portraits/men/11.jpg
https://randomuser.me/api/portraits/women/56.jpg
https://randomuser.me/api/portraits/men/69.jpg
https://randomuser.me/api/portraits/women/71.jpg
https://randomuser.me/api/portraits/women/80.jpg

In [47]:
def getting_users():
    users = []

    for user in RandomUser.generate_users(10):
       # users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
        users.append({"Name": user.get_full_name(), "Gender": user.get_gender(), "City": user.get_city(), "State": user.get_state(), "Email": user.get_email(), "Phone": user.get_phone(), "DOB": user.get_dob(), "Picture": user.get_picture()})

    return pd.DataFrame(users)

In [48]:
getting_users()

,Name,Gender,City,State,Email,Phone,DOB,Picture
0,Robert Fuller,male,Bunbury,Western Australia,robert.fuller@example.com,00-7053-2371,1955-01-15T18:54:37.497Z,https://randomuser.me/api/portraits/men/73.jpg
1,Borja Parra,male,Pontevedra,Castilla y León,borja.parra@example.com,985-336-476,1988-10-23T21:58:47.272Z,https://randomuser.me/api/portraits/men/26.jpg
2,Vital Alves,male,Bagé,Alagoas,vital.alves@example.com,(72) 2262-1787,1997-07-18T10:38:38.249Z,https://randomuser.me/api/portraits/men/2.jpg
3,Linnea Wuori,female,Virolahti,Southern Ostrobothnia,linnea.wuori@example.com,07-702-827,1968-11-06T05:21:55.501Z,https://randomuser.me/api/portraits/women/92.jpg
4,آرتين گلشن,male,کرج,کردستان,artyn.glshn@example.com,016-87538283,1989-12-18T20:03:27.066Z,https://randomuser.me/api/portraits/men/52.jpg
5,Marion Dubois,female,Nice,Seine-et-Marne,marion.dubois@example.com,05-38-18-51-92,1954-11-14T21:25:30.605Z,https://randomuser.me/api/portraits/women/14.jpg
6,Zoe Wang,female,Napier,West Coast,zoe.wang@example.com,(362)-557-6771,1963-10-26T20:32:46.422Z,https://randomuser.me/api/portraits/women/14.jpg
7,Rosário Martins,male,Angra dos Reis,Rio Grande do Norte,rosario.martins@example.com,(13) 6496-9128,1968-07-05T11:03:06.765Z,https://randomuser.me/api/portraits/men/84.jpg
8,Peppi Lehtinen,female,Pirkkala,Åland,peppi.lehtinen@example.com,05-721-939,1973-08-09T09:23:02.913Z,https://randomuser.me/api/portraits/women/21.jpg
9,Emil Mattila,male,Keitele,Kymenlaakso,emil.mattila@example.com,07-139-801,1987-04-04T12:25:29.959Z,https://randomuser.me/api/portraits/men/91.jpg

In [51]:
import requests
import json

In [52]:
data = requests.get("https://fruityvice.com/api/fruit/all")

In [54]:
results = json.loads(data.text)

In [55]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

In [56]:
df2 = pd.json_normalize(results)

In [57]:
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

In [63]:
banana = df2.loc[df2["name"] == 'Banana']
(banana.iloc[0]['family']) , (banana.iloc[0]['genus'])

('Musaceae', 'Musa')

In [64]:
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")

In [65]:
results2 = json.loads(data2.text)

In [ ]:
df3 = pd.DataFrame(results2)
df3.drop(columns=["type", "id"], inplace=True)
df3

,setup,punchline
0,What do you call a fashionable lawn statue wit...,A metro-gnome
1,Do you know where you can get chicken broth in...,The stock market.
2,What time is it?,I don't know... it keeps changing.
3,What do you call a droid that takes the long w...,R2 detour.
4,Did you hear about the runner who was criticized?,He just took it in stride
5,Why do birds fly south for the winter?,Because it's too far to walk.
6,"A SQL query walks into a bar, walks up to two ...",'Can I join you?'
7,How do you organize a space party?,You planet.
8,Why did the coffee file a police report?,It got mugged.
9,Why did the barber win the race?,He took a short cut.